site_name: HackTricks Without Ads

docs_dir: hacktricks # you can disable/remove this for faster testing

theme:
  name: material
  custom_dir: overrides
  features:
  - content.code.copy

plugins:
- search
- gitbook2mkdocs
- extract_listings:
    search_page_path: README.md
    search_page_create_if_missing: True
    javascript_search_file: assets/javascript/code-snippet-search.js

hooks:
- remove_ads.py
# - gitbook.py

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # for todo lists
  - pymdownx.tasklist:
      custom_checkbox: true
