site_name: HackTricks Without Ads

docs_dir: hacktricks # you can disable/remove this for faster testing

theme:
  name: material
  custom_dir: overrides
  features:
  - content.code.copy

hooks:
- hooks.py

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
